# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-09-27 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('moviename', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
